{
  "name": "zope.exceptions",
  "description": "=================\n zope.exceptions\n=================\n\n.. image:: https://img.shields.io/pypi/v/zope.exceptions.svg\n        :target: https://pypi.python.org/pypi/zope.exceptions/\n        :alt: Latest release\n\n.. image:: https://img.shields.io/pypi/pyversions/zope.exceptions.svg\n        :target: https://pypi.org/project/zope.exceptions/\n        :alt: Supported Python versions\n\n.. image:: https://travis-ci.org/zopefoundation/zope.exceptions.svg?branch=master\n        :target: https://travis-ci.org/zopefoundation/zope.exceptions\n\n.. image:: https://coveralls.io/repos/github/zopefoundation/zope.exceptions/badge.svg?branch=master\n        :target: https://coveralls.io/github/zopefoundation/zope.exceptions?branch=master\n\n.. image:: https://readthedocs.org/projects/zopeexceptions/badge/?version=latest\n        :target: https://zopeexceptions.readthedocs.io/en/latest/\n        :alt: Documentation Status\n\nThis package contains exception exceptions and implementations which are so\ngeneral purpose that they don't belong in Zope application-specific packages.\n\nPlease see https://zopeexceptions.readthedocs.io/ for the documentation.\n\n\n===========================\n zope.exceptions Changelog\n===========================\n\n4.4 (2020-07-16)\n================\n\n- Add support for Python 3.8 and preliminary support for 3.9b4.\n\n- Drop support for Python 3.4 and 3.5.\n\n\n4.3 (2018-10-04)\n================\n\n- Add support for Python 3.7.\n\n\n4.2.0 (2017-09-12)\n==================\n\n- Add support for Python 3.6.\n\n- Drop support for Python 3.3.\n\n- Fix handling of unicode supplemental traceback information on\n  Python 2. Now such values are always encoded to UTF-8; previously\n  the results were undefined and depended on system encodings and the\n  values themselves. See `issue 1 <https://github.com/zopefoundation/zope.exceptions/issues/1>`_.\n\n4.1.0 (2017-04-12)\n==================\n\n- Drop support for Python 2.6 and 3.2.\n\n- Make ``exceptionformatter.extract_stack`` signature comply with\n  ``traceback.extract_stack``\n\n- Add support for Python 3.5.\n\n4.0.8 (2015-08-13)\n==================\n\n- Fixes around ``TextExceptionFormatter`` ``limit``: ``formatException``\n  and ``extractStack`` was cutting the traceback at the bottom,\n  at the most interesting point. Now it will cut from the middle.\n  Some text about the missing entries will be inserted.\n\n- Maybe fix for ``extractStack``, it did not detect recursions in the frames.\n\n4.0.7 (2014-03-19)\n==================\n\n- Added explicit support for Python 3.4.\n\n- Updated ``boostrap.py`` to version 2.2.\n\n\n4.0.6 (2013-02-28)\n==================\n\n- Make sure that ``setup.py`` finds all tests. Now tox runs them all as well.\n\n- Fix failing test under Python 3.\n\n- Made buildout work under Python 3 and Buildout 2.\n\n\n4.0.5 (2012-12-31)\n==================\n\n- Fleshed out PyPI Trove classifiers.\n\n- Fixed a test failure under Python 2.6.\n\n\n4.0.4 (2012-12-13)\n==================\n\n- Release with a fixed MANIFEST.in (without ``docs/``)\n\n\n4.0.3 (2012-12-10)\n==================\n\n- Fixed format_exception(..., as_html=True) not to HTML-escape the '<br />'\n  it adds to the exception value.\n\n\n4.0.2 (2012-11-21)\n==================\n\n- Test Python 3.3 support under tox.\n\n\n4.0.1 (2012-08-20)\n==================\n\n- Fixed optional dependency code for `'zope.security`` to work under Python 3.3.\n\n\n4.0.0.1 (2012-05-16)\n====================\n\n- Fixed rendering of package docs on PyPI.\n\n\n4.0.0 (2012-05-16)\n==================\n\n- Automated build of Sphinx HTML docs and running doctest snippets via tox.\n\n- Added Sphinx documentation.\n\n- Added support for continuous integration using ``tox`` and ``jenkins``.\n\n- Removed use of '2to3' and associated fixers when installing under Py3k.\n  The code is now in a \"compatible subset\" which supports Python 2.6, 2.7,\n  and 3.2, including PyPy 1.8 (the version compatible with the 2.7 language\n  spec).\n\n- 100% unit test coverage.\n\n- Dropped explicit support for Python 2.4 / 2.5 / 3.1.\n\n- Added 'setup.py dev' alias (runs ``setup.py develop`` plus installs\n  ``nose`` and ``coverage``).\n\n- Added 'setup.py docs' alias (installs ``Sphinx`` and dependencies).\n\n\n3.7.1 (2012-03-28)\n==================\n\n- Fix: missed to reverse extractStack entries\n\n\n3.7.0 (2012-03-28)\n==================\n\n- Added TextExceptionFormatter.extractStack and extract_stack\n\n\n3.6.2 (2012-03-28)\n==================\n\n- Fallback to traceback.format_tb when the formatter is called recursively.\n  i.e. Don't let errors in the formatter pass silently.\n\n- Fix deprecated unittest functions: ``assert_`` and ``assertEquals``.\n\n3.6.1 (2010-07-06)\n==================\n\n- Fixed tests to work under Python 2.7.\n\n- PEP8 cleanup and removed obsolete build infrastructure files.\n\n\n3.6.0 (2010-05-02)\n==================\n\n- Added support to bootstrap on Jython.\n\n- Added Python 3 support.\n\n- The dependency on zope.testing seemed spurious, possibly a rest of a real\n  dependency that is gone now. I removed it.\n\n\n3.5.2 (2008-04-30)\n==================\n\n- Updated CHANGES.txt.\n\n\n3.5.1 (2008-04-28)\n==================\n\n- Reverted changes in 3.5.0.\n\n\n3.5.0\n=====\n\n- Added the capability for exceptions to be formatted line-by-line.\n  Unfortunately, also introduced a bug cause each line of the exception to be\n  its own log message.\n\n\n3.4.0 (2007-10-02)\n==================\n\n- Updated package meta-data.\n\n\n3.4.0b2 (2007-08-14)\n====================\n\n- Removed superfluous dependency on ``zope.deprecation``.\n\n\n3.4.0b1 (2007-07-09)\n====================\n\n- Corresponds to the version of the ``zope.exceptions`` package shipped as\n  part of the Zope 3.4.0b1 release.\n\n\n3.2.0 (2006-01-05)\n==================\n\n- Corresponds to the version of the ``zope.exceptions`` package shipped as part of\n  the Zope 3.2.0 release.\n\n- Deprecated the ``INotFoundError`` interface and the corresponding\n  ``NotFoundError`` exception class, in favor of \"standard\" exceptions\n  ``AttributeError``, ``KeyError``).  The deprecated items will be removed in\n  Zope 3.3.\n\n\n3.0.0 (2004-11-07)\n==================\n\n- Corresponds to the version of the zope.exceptions package shipped as part of\n  the Zope X3.0.0 release.\n\n\n",
  "requires_dist": [
    "setuptools",
    "zope.interface",
    "Sphinx ; extra == 'docs'",
    "repoze.sphinx.autointerface ; extra == 'docs'",
    "zope.testrunner ; extra == 'test'"
  ],
  "requires_python": "",
  "current_version": "4.4",
  "released_versions": [
    "3.4.0",
    "3.4dev",
    "3.5.0",
    "3.5.1",
    "3.5.2",
    "3.6.0",
    "3.6.1",
    "3.6.2",
    "3.7.0",
    "3.7.1",
    "4.0.0",
    "4.0.0.1",
    "4.0.1",
    "4.0.2",
    "4.0.3",
    "4.0.4",
    "4.0.5",
    "4.0.6",
    "4.0.7",
    "4.0.8",
    "4.1.0",
    "4.2.0",
    "4.3",
    "4.4"
  ]
}