[
  {
    "cveID": "CVE-2020-26275",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2020-12-21T18:15Z",
    "lastModifiedDate": "2021-03-30T19:15Z",
    "description": [
      {
        "lang": "en",
        "value": "The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila. In Jupyter Server before version 1.1.1, an open redirect vulnerability could cause the jupyter server to redirect the browser to a different malicious website. All jupyter servers running without a base_url prefix are technically affected, however, these maliciously crafted links can only be reasonably made for known jupyter server hosts. A link to your jupyter server may *appear* safe, but ultimately redirect to a spoofed server on the public internet. This same vulnerability was patched in upstream notebook v5.7.8. This is fixed in jupyter_server 1.1.1. If upgrade is not available, a workaround can be to run your server on a url prefix: \"jupyter server --ServerApp.base_url=/jupyter/\"."
      }
    ],
    "references": [
      {
        "url": "https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-9f66-54xg-pc2c",
        "name": "https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-9f66-54xg-pc2c",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/jupyter-server/",
        "name": "https://pypi.org/project/jupyter-server/",
        "refsource": "MISC",
        "tags": [
          "Product"
        ]
      },
      {
        "url": "https://github.com/jupyter-server/jupyter_server/commit/85e4abccf6ea9321d29153f73b0bd72ccb3a6bca",
        "name": "https://github.com/jupyter-server/jupyter_server/commit/85e4abccf6ea9321d29153f73b0bd72ccb3a6bca",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://advisory.checkmarx.net/advisory/CX-2020-4291",
        "name": "https://advisory.checkmarx.net/advisory/CX-2020-4291",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2021-2138",
    "cveASSIGNER": "secalert_us@oracle.com",
    "publishedDate": "2021-03-03T06:15Z",
    "lastModifiedDate": "2021-03-08T19:17Z",
    "description": [
      {
        "lang": "en",
        "value": "Vulnerability in the Oracle Cloud Infrastructure Data Science Notebook Sessions. Easily exploitable vulnerability allows low privileged attacker with access to the physical communication segment attached to the hardware where the Oracle Cloud Infrastructure Data Science Notebook Sessions executes to compromise Oracle Cloud Infrastructure Data Science Notebook Sessions. Successful attacks of this vulnerability can result in unauthorized update, insert or delete access to some of Oracle Cloud Infrastructure Data Science Notebook Sessions accessible data as well as unauthorized read access to a subset of Oracle Cloud Infrastructure Data Science Notebook Sessions accessible data. All affected customers were notified of CVE-2021-2138 by Oracle. CVSS 3.1 Base Score 4.6 (Confidentiality and Integrity impacts). CVSS Vector: (CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N)"
      }
    ],
    "references": [
      {
        "url": "https://support.oracle.com",
        "name": "https://support.oracle.com",
        "refsource": "MISC",
        "tags": [
          "Permissions Required"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-27225",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-03-01T01:15Z",
    "lastModifiedDate": "2021-03-05T20:09Z",
    "description": [
      {
        "lang": "en",
        "value": "In Dataiku DSS before 8.0.6, insufficient access control in the Jupyter notebooks integration allows users (who have coding permissions) to read and overwrite notebooks in projects that they are not authorized to access."
      }
    ],
    "references": [
      {
        "url": "https://doc.dataiku.com/dss/8.0/security/advisories/cve-2021-27225.html",
        "name": "https://doc.dataiku.com/dss/8.0/security/advisories/cve-2021-27225.html",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://doc.dataiku.com/dss/latest/",
        "name": "https://doc.dataiku.com/dss/latest/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-26261",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2020-12-09T17:15Z",
    "lastModifiedDate": "2020-12-10T21:46Z",
    "description": [
      {
        "lang": "en",
        "value": "jupyterhub-systemdspawner enables JupyterHub to spawn single-user notebook servers using systemd. In jupyterhub-systemdspawner before version 0.15 user API tokens issued to single-user servers are specified in the environment of systemd units. These tokens are incorrectly accessible to all users. In particular, the-littlest-jupyterhub is affected, which uses systemdspawner by default. This is patched in jupyterhub-systemdspawner v0.15"
      }
    ],
    "references": [
      {
        "url": "https://github.com/jupyterhub/systemdspawner/security/advisories/GHSA-cg54-gpgr-4rm6",
        "name": "https://github.com/jupyterhub/systemdspawner/security/advisories/GHSA-cg54-gpgr-4rm6",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyterhub/systemdspawner/commit/a4d08fd2ade1cfd0ef2c29dc221e649345f23580",
        "name": "https://github.com/jupyterhub/systemdspawner/commit/a4d08fd2ade1cfd0ef2c29dc221e649345f23580",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/jupyterhub-systemdspawner/",
        "name": "https://pypi.org/project/jupyterhub-systemdspawner/",
        "refsource": "MISC",
        "tags": [
          "Product",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyterhub/systemdspawner/blob/master/CHANGELOG.md#v015",
        "name": "https://github.com/jupyterhub/systemdspawner/blob/master/CHANGELOG.md#v015",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-26215",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2020-11-18T22:15Z",
    "lastModifiedDate": "2020-12-03T15:59Z",
    "description": [
      {
        "lang": "en",
        "value": "Jupyter Notebook before version 6.1.5 has an Open redirect vulnerability. A maliciously crafted link to a notebook server could redirect the browser to a different website. All notebook servers are technically affected, however, these maliciously crafted links can only be reasonably made for known notebook server hosts. A link to your notebook server may appear safe, but ultimately redirect to a spoofed server on the public internet. The issue is patched in version 6.1.5."
      }
    ],
    "references": [
      {
        "url": "https://github.com/jupyter/notebook/security/advisories/GHSA-c7vm-f5p4-8fqh",
        "name": "https://github.com/jupyter/notebook/security/advisories/GHSA-c7vm-f5p4-8fqh",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyter/notebook/commit/3cec4bbe21756de9f0c4bccf18cf61d840314d74",
        "name": "https://github.com/jupyter/notebook/commit/3cec4bbe21756de9f0c4bccf18cf61d840314d74",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/12/msg00004.html",
        "name": "[debian-lts-announce] 20201202 [SECURITY] [DLA 2477-1] jupyter-notebook security update",
        "refsource": "MLIST",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-8354",
    "cveASSIGNER": "psirt@lenovo.com",
    "publishedDate": "2020-11-11T18:15Z",
    "lastModifiedDate": "2020-11-30T14:42Z",
    "description": [
      {
        "lang": "en",
        "value": "A potential vulnerability in the SMI callback function used in the VariableServiceSmm driver in some Lenovo Notebook models may allow arbitrary code execution."
      }
    ],
    "references": [
      {
        "url": "https://support.lenovo.com/us/en/product_security/LEN-49266",
        "name": "https://support.lenovo.com/us/en/product_security/LEN-49266",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2018-8768",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2018-03-18T06:29Z",
    "lastModifiedDate": "2020-11-19T07:15Z",
    "description": [
      {
        "lang": "en",
        "value": "In Jupyter Notebook before 5.4.1, a maliciously forged notebook file can bypass sanitization to execute JavaScript in the notebook context. Specifically, invalid HTML is 'fixed' by jQuery after sanitization, making it dangerous."
      }
    ],
    "references": [
      {
        "url": "http://openwall.com/lists/oss-security/2018/03/15/2",
        "name": "http://openwall.com/lists/oss-security/2018/03/15/2",
        "refsource": "CONFIRM",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html",
        "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2432-1] jupyter-notebook security update",
        "refsource": "MLIST",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2018-21030",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2019-10-31T15:15Z",
    "lastModifiedDate": "2020-11-19T07:15Z",
    "description": [
      {
        "lang": "en",
        "value": "Jupyter Notebook before 5.5.0 does not use a CSP header to treat served files as belonging to a separate origin. Thus, for example, an XSS payload can be placed in an SVG document."
      }
    ],
    "references": [
      {
        "url": "https://github.com/jupyter/notebook/releases/tag/5.5.0",
        "name": "https://github.com/jupyter/notebook/releases/tag/5.5.0",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyter/notebook/pull/3341",
        "name": "https://github.com/jupyter/notebook/pull/3341",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html",
        "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2432-1] jupyter-notebook security update",
        "refsource": "MLIST",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2018-19351",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2018-11-18T17:29Z",
    "lastModifiedDate": "2020-11-19T07:15Z",
    "description": [
      {
        "lang": "en",
        "value": "Jupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this."
      }
    ],
    "references": [
      {
        "url": "https://pypi.org/project/notebook/#history",
        "name": "https://pypi.org/project/notebook/#history",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY",
        "name": "https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491",
        "name": "https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst",
        "name": "https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst",
        "refsource": "MISC",
        "tags": [
          "Release Notes"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html",
        "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2432-1] jupyter-notebook security update",
        "refsource": "MLIST",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-4724",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-10-29T16:15Z",
    "lastModifiedDate": "2020-10-30T21:52Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.0 and 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6356497",
        "name": "https://www.ibm.com/support/pages/node/6356497",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/187874",
        "name": "ibm-i2-cve20204724-bo (187874)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4721",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-10-29T16:15Z",
    "lastModifiedDate": "2020-10-30T21:52Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.0 and 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 187868."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6356497",
        "name": "https://www.ibm.com/support/pages/node/6356497",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/187868",
        "name": "ibm-i2-cve20204721-bo (187868)",
        "refsource": "XF",
        "tags": [
          "VDB Entry"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4722",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-10-29T16:15Z",
    "lastModifiedDate": "2020-10-30T21:51Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.0 and 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 187870."
      }
    ],
    "references": [
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/187870",
        "name": "ibm-i2-cve20204722-bo (187870)",
        "refsource": "XF",
        "tags": [
          "VDB Entry"
        ]
      },
      {
        "url": "https://www.ibm.com/support/pages/node/6356497",
        "name": "https://www.ibm.com/support/pages/node/6356497",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4723",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-10-29T16:15Z",
    "lastModifiedDate": "2020-10-30T21:51Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.0 and 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 187873."
      }
    ],
    "references": [
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/187873",
        "name": "ibm-i2-cve20204723-bo (187873)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://www.ibm.com/support/pages/node/6356497",
        "name": "https://www.ibm.com/support/pages/node/6356497",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-16977",
    "cveASSIGNER": "secure@microsoft.com",
    "publishedDate": "2020-10-16T23:15Z",
    "lastModifiedDate": "2020-10-20T16:22Z",
    "description": [
      {
        "lang": "en",
        "value": "A remote code execution vulnerability exists in Visual Studio Code when the Python extension loads a Jupyter notebook file, aka 'Visual Studio Code Python Extension Remote Code Execution Vulnerability'."
      }
    ],
    "references": [
      {
        "url": "https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-16977",
        "name": "https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-16977",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4550",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:27Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 and 9.2.2 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183318."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183318",
        "name": "ibm-i2-cve20204550-bo (183318)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4551",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:23Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 and 9.2.2 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183319."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183319",
        "name": "ibm-i2-cve20204551-bo (183319)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4552",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:23Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183320."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183320",
        "name": "ibm-i2-cve20204552-bo (183320)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4554",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:23Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 and 9.2.2 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183322."
      }
    ],
    "references": [
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183322",
        "name": "ibm-i2-cve20204554-bo (183322)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4553",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:23Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 and 9.2.2 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183321."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183321",
        "name": "ibm-i2-cve20204553-bo (183321)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-4549",
    "cveASSIGNER": "psirt@us.ibm.com",
    "publishedDate": "2020-08-03T13:15Z",
    "lastModifiedDate": "2020-08-03T18:23Z",
    "description": [
      {
        "lang": "en",
        "value": "IBM i2 Analyst Notebook 9.2.1 could allow a local attacker to execute arbitrary code on the system, caused by a memory corruption. By persuading a victim to open a specially-crafted file, an attacker could exploit this vulnerability to execute arbitrary code on the system. IBM X-Force ID: 183317."
      }
    ],
    "references": [
      {
        "url": "https://www.ibm.com/support/pages/node/6254694",
        "name": "https://www.ibm.com/support/pages/node/6254694",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/183317",
        "name": "ibm-i2-cve20204549-bo (183317)",
        "refsource": "XF",
        "tags": [
          "VDB Entry",
          "Vendor Advisory"
        ]
      }
    ]
  }
]