[
  {
    "cveID": "CVE-2020-26116",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2020-09-27T04:15Z",
    "lastModifiedDate": "2021-01-26T18:15Z",
    "description": [
      {
        "lang": "en",
        "value": "http.client in Python 3.x before 3.5.10, 3.6.x before 3.6.12, 3.7.x before 3.7.9, and 3.8.x before 3.8.5 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of HTTPConnection.request."
      }
    ],
    "references": [
      {
        "url": "https://bugs.python.org/issue39603",
        "name": "https://bugs.python.org/issue39603",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html",
        "name": "https://python-security.readthedocs.io/vuln/http-header-injection-method.html",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BW4GCLQISJCOEGQNIMVUZDQMIY6RR6CC/",
        "name": "FEDORA-2020-221823ebdd",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OXI72HIHMXCQFWTULUXDG7VDA2BCYL4Y/",
        "name": "FEDORA-2020-d30881c970",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JWMAVY4T4257AZHTF2RZJKNJNSJFY24O/",
        "name": "FEDORA-2020-887d3fa26f",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://usn.ubuntu.com/4581-1/",
        "name": "USN-4581-1",
        "refsource": "UBUNTU",
        "tags": []
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20201023-0001/",
        "name": "https://security.netapp.com/advisory/ntap-20201023-0001/",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HDQ2THWU4GPV4Y5H5WW5PFMSWXL2CRFD/",
        "name": "FEDORA-2020-e33acdea18",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2020-11/msg00027.html",
        "name": "openSUSE-SU-2020:1859",
        "refsource": "SUSE",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QOX7DGMMWWL6POCRYGAUCISOLR2IG3XV/",
        "name": "FEDORA-2020-d42cb01973",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00032.html",
        "name": "[debian-lts-announce] 20201119 [SECURITY] [DLA 2456-1] python3.5 security update",
        "refsource": "MLIST",
        "tags": []
      },
      {
        "url": "https://security.gentoo.org/glsa/202101-18",
        "name": "GLSA-202101-18",
        "refsource": "GENTOO",
        "tags": []
      }
    ]
  }
]