[
  {
    "cveID": "CVE-2021-31542",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-05-05T15:15Z",
    "lastModifiedDate": "2021-05-13T13:41Z",
    "description": [
      {
        "lang": "en",
        "value": "In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names."
      }
    ],
    "references": [
      {
        "url": "https://www.djangoproject.com/weblog/2021/may/04/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2021/may/04/security-releases/",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/3.2/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.2/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2021/05/04/3",
        "name": "http://www.openwall.com/lists/oss-security/2021/05/04/3",
        "refsource": "MISC",
        "tags": [
          "Mailing List",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!forum/django-announce",
        "name": "https://groups.google.com/forum/#!forum/django-announce",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00005.html",
        "name": "[debian-lts-announce] 20210506 [SECURITY] [DLA 2651-1] python-django security update",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/",
        "name": "FEDORA-2021-01044b8a59",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-32052",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-05-06T16:15Z",
    "lastModifiedDate": "2021-05-12T08:15Z",
    "description": [
      {
        "lang": "en",
        "value": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers."
      }
    ],
    "references": [
      {
        "url": "https://docs.djangoproject.com/en/3.2/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.2/releases/security/",
        "refsource": "MISC",
        "tags": []
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2021/05/06/1",
        "name": "http://www.openwall.com/lists/oss-security/2021/05/06/1",
        "refsource": "MISC",
        "tags": []
      },
      {
        "url": "https://groups.google.com/forum/#!forum/django-announce",
        "name": "https://groups.google.com/forum/#!forum/django-announce",
        "refsource": "MISC",
        "tags": []
      },
      {
        "url": "https://www.djangoproject.com/weblog/2021/may/06/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2021/may/06/security-releases/",
        "refsource": "MISC",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/",
        "name": "FEDORA-2021-01044b8a59",
        "refsource": "FEDORA",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2021-28658",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-04-06T15:15Z",
    "lastModifiedDate": "2021-05-12T08:15Z",
    "description": [
      {
        "lang": "en",
        "value": "In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability."
      }
    ],
    "references": [
      {
        "url": "https://groups.google.com/g/django-announce/c/ePr5j-ngdPU",
        "name": "https://groups.google.com/g/django-announce/c/ePr5j-ngdPU",
        "refsource": "MISC",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2021/apr/06/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2021/apr/06/security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/3.1/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.1/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2021/04/msg00008.html",
        "name": "[debian-lts-announce] 20210409 [SECURITY] [DLA 2622-1] python-django security update",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZVKYPHR3TKR2ESWXBPOJEKRO2OSJRZUE/",
        "name": "FEDORA-2021-01044b8a59",
        "refsource": "FEDORA",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-15225",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2021-04-29T21:15Z",
    "lastModifiedDate": "2021-05-10T17:55Z",
    "description": [
      {
        "lang": "en",
        "value": "django-filter is a generic system for filtering Django QuerySets based on user selections. In django-filter before version 2.4.0, automatically generated `NumberFilter` instances, whose value was later converted to an integer, were subject to potential DoS from maliciously input using exponential format with sufficiently large exponents. Version 2.4.0+ applies a `MaxValueValidator` with a a default `limit_value` of 1e50 to the form field used by `NumberFilter` instances. In addition, `NumberFilter` implements the new `get_max_validator()` which should return a configured validator instance to customise the limit, or else `None` to disable the additional validation. Users may manually apply an equivalent validator if they are not able to upgrade."
      }
    ],
    "references": [
      {
        "url": "https://github.com/carltongibson/django-filter/security/advisories/GHSA-x7gm-rfgv-w973",
        "name": "https://github.com/carltongibson/django-filter/security/advisories/GHSA-x7gm-rfgv-w973",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/carltongibson/django-filter/commit/340cf7a23a2b3dcd7183f6a0d6c383e85b130d2b",
        "name": "https://github.com/carltongibson/django-filter/commit/340cf7a23a2b3dcd7183f6a0d6c383e85b130d2b",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/django-filter/",
        "name": "https://pypi.org/project/django-filter/",
        "refsource": "MISC",
        "tags": [
          "Product",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/carltongibson/django-filter/releases/tag/2.4.0",
        "name": "https://github.com/carltongibson/django-filter/releases/tag/2.4.0",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-29434",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2021-04-19T19:15Z",
    "lastModifiedDate": "2021-04-29T14:24Z",
    "description": [
      {
        "lang": "en",
        "value": "Wagtail is a Django content management system. In affected versions of Wagtail, when saving the contents of a rich text field in the admin interface, Wagtail does not apply server-side checks to ensure that link URLs use a valid protocol. A malicious user with access to the admin interface could thus craft a POST request to publish content with `javascript:` URLs containing arbitrary code. The vulnerability is not exploitable by an ordinary site visitor without access to the Wagtail admin. See referenced GitHub advisory for additional details, including a workaround. Patched versions have been released as Wagtail 2.11.7 (for the LTS 2.11 branch) and Wagtail 2.12.4 (for the current 2.12 branch)."
      }
    ],
    "references": [
      {
        "url": "https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx",
        "name": "https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx",
        "refsource": "CONFIRM",
        "tags": [
          "Mitigation",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/wagtail/",
        "name": "https://pypi.org/project/wagtail/",
        "refsource": "MISC",
        "tags": [
          "Product",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-30459",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-04-14T18:15Z",
    "lastModifiedDate": "2021-04-21T15:05Z",
    "description": [
      {
        "lang": "en",
        "value": "A SQL Injection issue in the SQL Panel in Jazzband Django Debug Toolbar before 1.11.1, 2.x before 2.2.1, and 3.x before 3.2.1 allows attackers to execute SQL statements by changing the raw_sql input field of the SQL explain, analyze, or select form."
      }
    ],
    "references": [
      {
        "url": "https://github.com/jazzband/django-debug-toolbar/security/advisories/GHSA-pghf-347x-c2gj",
        "name": "https://github.com/jazzband/django-debug-toolbar/security/advisories/GHSA-pghf-347x-c2gj",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2021/apr/14/debug-toolbar-security-releases/",
        "name": "https://www.djangoproject.com/weblog/2021/apr/14/debug-toolbar-security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://github.com/jazzband/django-debug-toolbar/releases",
        "name": "https://github.com/jazzband/django-debug-toolbar/releases",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2013-3587",
    "cveASSIGNER": "cert@cert.org",
    "publishedDate": "2020-02-21T18:15Z",
    "lastModifiedDate": "2021-04-10T01:15Z",
    "description": [
      {
        "lang": "en",
        "value": "The HTTPS protocol, as used in unspecified web applications, can encrypt compressed data without properly obfuscating the length of the unencrypted data, which makes it easier for man-in-the-middle attackers to obtain plaintext secret values by observing length differences during a series of guesses in which a string in an HTTP request URL potentially matches an unknown string in an HTTP response body, aka a \"BREACH\" attack, a different issue than CVE-2012-4929."
      }
    ],
    "references": [
      {
        "url": "http://security.stackexchange.com/questions/20406/is-http-compression-safe#20407",
        "name": "http://security.stackexchange.com/questions/20406/is-http-compression-safe#20407",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://slashdot.org/story/13/08/05/233216",
        "name": "http://slashdot.org/story/13/08/05/233216",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://breachattack.com/",
        "name": "http://breachattack.com/",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.blackhat.com/us-13/briefings.html#Prado",
        "name": "https://www.blackhat.com/us-13/briefings.html#Prado",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://hackerone.com/reports/254895",
        "name": "https://hackerone.com/reports/254895",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.iacr.org/cryptodb/archive/2002/FSE/3091/3091.pdf",
        "name": "http://www.iacr.org/cryptodb/archive/2002/FSE/3091/3091.pdf",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.kb.cert.org/vuls/id/987798",
        "name": "http://www.kb.cert.org/vuls/id/987798",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory",
          "US Government Resource"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=995168",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=995168",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://support.f5.com/csp/article/K14634",
        "name": "https://support.f5.com/csp/article/K14634",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://github.com/meldium/breach-mitigation-rails",
        "name": "http://github.com/meldium/breach-mitigation-rails",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2013/aug/06/breach-and-django/",
        "name": "https://www.djangoproject.com/weblog/2013/aug/06/breach-and-django/",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.apache.org/thread.html/r7f0e9cfd166934172d43ca4c272b8bdda4a343036229d9937affd1e1@%3Cdev.httpd.apache.org%3E",
        "name": "[httpd-dev] 20210409 GSOC project Idea- fix for CVE-2013-3587",
        "refsource": "MLIST",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2021-21416",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2021-04-01T22:15Z",
    "lastModifiedDate": "2021-04-06T18:40Z",
    "description": [
      {
        "lang": "en",
        "value": "django-registration is a user registration package for Django. The django-registration package provides tools for implementing user-account registration flows in the Django web framework. In django-registration prior to 3.1.2, the base user-account registration view did not properly apply filters to sensitive data, with the result that sensitive data could be included in error reports rather than removed automatically by Django. Triggering this requires: A site is using django-registration < 3.1.2, The site has detailed error reports (such as Django's emailed error reports to site staff/developers) enabled and a server-side error (HTTP 5xx) occurs during an attempt by a user to register an account. Under these conditions, recipients of the detailed error report will see all submitted data from the account-registration attempt, which may include the user's proposed credentials (such as a password)."
      }
    ],
    "references": [
      {
        "url": "https://github.com/ubernostrum/django-registration/security/advisories/GHSA-58c7-px5v-82hh",
        "name": "https://github.com/ubernostrum/django-registration/security/advisories/GHSA-58c7-px5v-82hh",
        "refsource": "CONFIRM",
        "tags": [
          "Mitigation",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-21377",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2021-03-23T16:15Z",
    "lastModifiedDate": "2021-03-27T02:20Z",
    "description": [
      {
        "lang": "en",
        "value": "OMERO.web is open source Django-based software for managing microscopy imaging. OMERO.web before version 5.9.0 supports redirection to a given URL after performing login or switching the group context. These URLs are not validated, allowing redirection to untrusted sites. OMERO.web 5.9.0 adds URL validation before redirecting. External URLs are not considered valid, unless specified in the omero.web.redirect_allowed_hosts setting."
      }
    ],
    "references": [
      {
        "url": "https://github.com/ome/omero-web/blob/master/CHANGELOG.md#590-march-2021",
        "name": "https://github.com/ome/omero-web/blob/master/CHANGELOG.md#590-march-2021",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/omero-web/",
        "name": "https://pypi.org/project/omero-web/",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/ome/omero-web/commit/952f8e5d28532fbb14fb665982211329d137908c",
        "name": "https://github.com/ome/omero-web/commit/952f8e5d28532fbb14fb665982211329d137908c",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.openmicroscopy.org/security/advisories/2021-SV2/",
        "name": "https://www.openmicroscopy.org/security/advisories/2021-SV2/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://github.com/ome/omero-web/security/advisories/GHSA-g4rf-pc26-6hmr",
        "name": "https://github.com/ome/omero-web/security/advisories/GHSA-g4rf-pc26-6hmr",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-21376",
    "cveASSIGNER": "security-advisories@github.com",
    "publishedDate": "2021-03-23T16:15Z",
    "lastModifiedDate": "2021-03-27T01:59Z",
    "description": [
      {
        "lang": "en",
        "value": "OMERO.web is open source Django-based software for managing microscopy imaging. OMERO.web before version 5.9.0 loads various information about the current user such as their id, name and the groups they are in, and these are available on the main webclient pages. This represents an information exposure vulnerability. Some additional information being loaded is not used by the webclient and is being removed in this release. This is fixed in version 5.9.0."
      }
    ],
    "references": [
      {
        "url": "https://github.com/ome/omero-web/blob/master/CHANGELOG.md#590-march-2021",
        "name": "https://github.com/ome/omero-web/blob/master/CHANGELOG.md#590-march-2021",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://pypi.org/project/omero-web/",
        "name": "https://pypi.org/project/omero-web/",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/ome/omero-web/security/advisories/GHSA-gfp2-w5jm-955q",
        "name": "https://github.com/ome/omero-web/security/advisories/GHSA-gfp2-w5jm-955q",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.openmicroscopy.org/security/advisories/2021-SV1/",
        "name": "https://www.openmicroscopy.org/security/advisories/2021-SV1/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://github.com/ome/omero-web/commit/952f8e5d28532fbb14fb665982211329d137908c",
        "name": "https://github.com/ome/omero-web/commit/952f8e5d28532fbb14fb665982211329d137908c",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2018-16552",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2018-09-05T22:29Z",
    "lastModifiedDate": "2021-03-11T16:20Z",
    "description": [
      {
        "lang": "en",
        "value": "MicroPyramid Django-CRM 0.2 allows CSRF for /users/create/, /users/##/edit/, and /accounts/##/delete/ URIs."
      }
    ],
    "references": [
      {
        "url": "https://github.com/MicroPyramid/Django-CRM/issues/68",
        "name": "https://github.com/MicroPyramid/Django-CRM/issues/68",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2012-5474",
    "cveASSIGNER": "secalert@redhat.com",
    "publishedDate": "2019-12-30T20:15Z",
    "lastModifiedDate": "2021-03-09T14:45Z",
    "description": [
      {
        "lang": "en",
        "value": "The file /etc/openstack-dashboard/local_settings within Red Hat OpenStack Platform 2.0 and RHOS Essex Release (python-django-horizon package before 2012.1.1) is world readable and exposes the secret key value."
      }
    ],
    "references": [
      {
        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2012-November/092841.html",
        "name": "http://lists.fedoraproject.org/pipermail/package-announce/2012-November/092841.html",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://access.redhat.com/security/cve/cve-2012-5474",
        "name": "https://access.redhat.com/security/cve/cve-2012-5474",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2012-5474",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2012-5474",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security-tracker.debian.org/tracker/CVE-2012-5474",
        "name": "https://security-tracker.debian.org/tracker/CVE-2012-5474",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2021-3281",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-02-02T07:15Z",
    "lastModifiedDate": "2021-03-05T19:19Z",
    "description": [
      {
        "lang": "en",
        "value": "In Django 2.2 before 2.2.18, 3.0 before 3.0.12, and 3.1 before 3.1.6, the django.utils.archive.extract method (used by \"startapp --template\" and \"startproject --template\") allows directory traversal via an archive with absolute paths or relative paths with dot segments."
      }
    ],
    "references": [
      {
        "url": "https://docs.djangoproject.com/en/3.1/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.1/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2021/feb/01/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2021/feb/01/security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!forum/django-announce",
        "name": "https://groups.google.com/forum/#!forum/django-announce",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YF52FKEH5S2P5CM4X7IXSYG67YY2CDOO/",
        "name": "FEDORA-2021-5329c680f7",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20210226-0004/",
        "name": "https://security.netapp.com/advisory/ntap-20210226-0004/",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-35681",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2021-02-22T03:15Z",
    "lastModifiedDate": "2021-02-26T12:36Z",
    "description": [
      {
        "lang": "en",
        "value": "Django Channels 3.x before 3.0.3 allows remote attackers to obtain sensitive information from a different request scope. The legacy channels.http.AsgiHandler class, used for handling HTTP type requests in an ASGI environment prior to Django 3.0, did not correctly separate request scopes in Channels 3.0. In many cases this would result in a crash but, with correct timing, responses could be sent to the wrong client, resulting in potential leakage of session identifiers and other sensitive data. Note that this affects only the legacy Channels provided class, and not Django's similar ASGIHandler, available from Django 3.0."
      }
    ],
    "references": [
      {
        "url": "https://github.com/django/channels/releases",
        "name": "https://github.com/django/channels/releases",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://channels.readthedocs.io/en/stable/releases/3.0.3.html",
        "name": "https://channels.readthedocs.io/en/stable/releases/3.0.3.html",
        "refsource": "CONFIRM",
        "tags": [
          "Exploit",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://channels.readthedocs.io/en/stable/releases/index.html",
        "name": "https://channels.readthedocs.io/en/stable/releases/index.html",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2020-24584",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2020-09-01T13:15Z",
    "lastModifiedDate": "2021-01-20T15:15Z",
    "description": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077."
      }
    ],
    "references": [
      {
        "url": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
        "name": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
        "name": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
        "refsource": "MISC",
        "tags": [
          "Mailing List",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
        "name": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/dev/releases/security/",
        "name": "https://docs.djangoproject.com/en/dev/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4479-1/",
        "name": "USN-4479-1",
        "refsource": "UBUNTU",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/",
        "name": "FEDORA-2020-94407454d7",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/",
        "name": "FEDORA-2020-6941c0a65b",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20200918-0004/",
        "name": "https://security.netapp.com/advisory/ntap-20200918-0004/",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/",
        "name": "FEDORA-2020-9c6b391162",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-24583",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2020-09-01T13:15Z",
    "lastModifiedDate": "2021-01-20T15:15Z",
    "description": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command."
      }
    ],
    "references": [
      {
        "url": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
        "name": "https://groups.google.com/forum/#!topic/django-announce/Gdqn58RqIDM",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
        "name": "https://www.openwall.com/lists/oss-security/2020/09/01/2",
        "refsource": "MISC",
        "tags": [
          "Mailing List",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
        "name": "https://groups.google.com/forum/#!topic/django-announce/zFCMdgUnutU",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2020/sep/01/security-releases/",
        "refsource": "MISC",
        "tags": [
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/dev/releases/security/",
        "name": "https://docs.djangoproject.com/en/dev/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4479-1/",
        "name": "USN-4479-1",
        "refsource": "UBUNTU",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/",
        "name": "FEDORA-2020-94407454d7",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/",
        "name": "FEDORA-2020-6941c0a65b",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20200918-0004/",
        "name": "https://security.netapp.com/advisory/ntap-20200918-0004/",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/",
        "name": "FEDORA-2020-9c6b391162",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-13596",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2020-06-03T14:15Z",
    "lastModifiedDate": "2021-01-20T15:15Z",
    "description": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack."
      }
    ],
    "references": [
      {
        "url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
        "name": "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/3.0/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.0/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4381-1/",
        "name": "USN-4381-1",
        "refsource": "UBUNTU",
        "tags": []
      },
      {
        "url": "https://usn.ubuntu.com/4381-2/",
        "name": "USN-4381-2",
        "refsource": "UBUNTU",
        "tags": []
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20200611-0002/",
        "name": "https://security.netapp.com/advisory/ntap-20200611-0002/",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://www.debian.org/security/2020/dsa-4705",
        "name": "DSA-4705",
        "refsource": "DEBIAN",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
        "name": "FEDORA-2020-c2639662af",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-13254",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2020-06-03T14:15Z",
    "lastModifiedDate": "2021-01-20T15:15Z",
    "description": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage."
      }
    ],
    "references": [
      {
        "url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/3.0/releases/security/",
        "name": "https://docs.djangoproject.com/en/3.0/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Release Notes",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
        "name": "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
        "refsource": "MISC",
        "tags": [
          "Mailing List",
          "Release Notes",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4381-1/",
        "name": "USN-4381-1",
        "refsource": "UBUNTU",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4381-2/",
        "name": "USN-4381-2",
        "refsource": "UBUNTU",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20200611-0002/",
        "name": "https://security.netapp.com/advisory/ntap-20200611-0002/",
        "refsource": "CONFIRM",
        "tags": []
      },
      {
        "url": "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html",
        "name": "[debian-lts-announce] 20200612 [SECURITY] [DLA 2233-2] python-django regression update",
        "refsource": "MLIST",
        "tags": []
      },
      {
        "url": "https://www.debian.org/security/2020/dsa-4705",
        "name": "DSA-4705",
        "refsource": "DEBIAN",
        "tags": []
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
        "name": "FEDORA-2020-c2639662af",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "name": "https://www.oracle.com/security-alerts/cpujan2021.html",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2020-25626",
    "cveASSIGNER": "secalert@redhat.com",
    "publishedDate": "2020-09-30T20:15Z",
    "lastModifiedDate": "2020-10-16T11:15Z",
    "description": [
      {
        "lang": "en",
        "value": "A flaw was found in Django REST Framework versions before 3.12.0 and before 3.11.2. When using the browseable API viewer, Django REST Framework fails to properly escape certain strings that can come from user input. This allows a user who can control those strings to inject malicious <script> tags, leading to a cross-site-scripting (XSS) vulnerability."
      }
    ],
    "references": [
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1878635",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1878635",
        "refsource": "MISC",
        "tags": [
          "Issue Tracking",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20201016-0003/",
        "name": "https://security.netapp.com/advisory/ntap-20201016-0003/",
        "refsource": "CONFIRM",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2019-12781",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2019-07-01T14:15Z",
    "lastModifiedDate": "2020-08-24T17:37Z",
    "description": [
      {
        "lang": "en",
        "value": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP."
      }
    ],
    "references": [
      {
        "url": "https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ",
        "name": "https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ",
        "refsource": "MISC",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/",
        "name": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "https://docs.djangoproject.com/en/dev/releases/security/",
        "name": "https://docs.djangoproject.com/en/dev/releases/security/",
        "refsource": "MISC",
        "tags": [
          "Patch",
          "Vendor Advisory"
        ]
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2019/07/01/3",
        "name": "[oss-security] 20190701 Django: CVE-2019-12781: Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://usn.ubuntu.com/4043-1/",
        "name": "USN-4043-1",
        "refsource": "UBUNTU",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/109018",
        "name": "109018",
        "refsource": "BID",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://security.netapp.com/advisory/ntap-20190705-0002/",
        "name": "https://security.netapp.com/advisory/ntap-20190705-0002/",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://www.debian.org/security/2019/dsa-4476",
        "name": "DSA-4476",
        "refsource": "DEBIAN",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://seclists.org/bugtraq/2019/Jul/10",
        "name": "20190708 [SECURITY] [DSA 4476-1] python-django security update",
        "refsource": "BUGTRAQ",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL/",
        "name": "FEDORA-2019-d9aa58d863",
        "refsource": "FEDORA",
        "tags": []
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html",
        "name": "openSUSE-SU-2019:1839",
        "refsource": "SUSE",
        "tags": []
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html",
        "name": "openSUSE-SU-2019:1872",
        "refsource": "SUSE",
        "tags": []
      }
    ]
  }
]